-- section2 
-- READ UNCOMMITTED
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
START TRANSACTION;
SELECT * FROM User_account WHERE ID = '003';

-- READ COMMITTED
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
    INSERT INTO User_account (ID, Name, Balance) VALUES ('004', 'abcd', '10000');
COMMIT;



-- REPEATABLE READ
START TRANSACTION;

UPDATE User_account
SET Balance = Balance + 1000
WHERE ID = 005;
COMMIT;


-- SERIALIZABLE
START TRANSACTION;

INSERT INTO User_account (ID, Name, Balance)
VALUES (006, 'F', 9999);
