-- section 1
-- READ UNCOMMITTED
Select * from User_account where ID = '003'; -- check info before question
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
START TRANSACTION;

UPDATE User_account
SET Balance = Balance - 100000
WHERE ID = '003';

rollback;

-- READ COMMITTED
START TRANSACTION;
    UPDATE User_account SET Balance= 1000 WHERE ID = 004;
COMMIT;
    SELECT * FROM User_account WHERE ID = 004;


-- REPEATABLE READ
-- run this first then go to section2
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
START TRANSACTION;

SELECT * FROM User_account WHERE ID = 005;

-- run this after running sectiob 2
SELECT * FROM User_account WHERE ID = 005;
COMMIT;


-- SERIALIZABLE 
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
START TRANSACTION;

SELECT * FROM User_account WHERE ID = 3;
COMMIT;
